# Generated by Django 3.2.7 on 2021-10-01 11:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscapeRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('story', models.TextField()),
                ('number_of_players', models.IntegerField()),
                ('city', models.CharField(choices=[('K', 'Karaj'), ('T', 'Tehran')], max_length=1)),
                ('age', models.IntegerField()),
                ('genre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReserveDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(choices=[('1', datetime.time(11, 0)), ('2', datetime.time(11, 30)), ('3', datetime.time(12, 0)), ('4', datetime.time(12, 30)), ('5', datetime.time(13, 30))])),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.escaperoom')),
            ],
        ),
    ]
