# Generated by Django 3.2.7 on 2021-10-01 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedate',
            name='activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservedate',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservedate',
            name='reserve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.escaperoom'),
        ),
    ]
