# Generated by Django 3.2.7 on 2021-10-01 11:49

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20211001_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedate',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
