# Generated by Django 3.2.7 on 2021-10-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_reservedate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedate',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
