# Generated by Django 3.2.7 on 2021-10-01 11:52

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_reservedate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedate',
            name='jdate',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
