# Generated by Django 3.2.7 on 2021-10-01 11:58

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_reservedate_jdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='reservedate',
            name='jdate',
        ),
    ]
