# Generated by Django 3.2.7 on 2021-10-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20211001_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ok',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
