# Generated by Django 3.2.7 on 2021-10-01 12:28

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_ok_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ok',
            name='date',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
