# Generated by Django 3.2.7 on 2021-10-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_ok_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OK',
        ),
    ]
