# Generated by Django 3.2.7 on 2021-10-01 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_reservedate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedate',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservedate',
            name='date',
            field=models.DateField(),
        ),
    ]
