# Generated by Django 3.2.7 on 2021-10-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_remove_reservedate_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedate',
            name='tm',
            field=models.TimeField(null=True),
        ),
    ]
