# Generated by Django 3.2.7 on 2021-10-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_t'),
    ]

    operations = [
        migrations.DeleteModel(
            name='T',
        ),
        migrations.AlterField(
            model_name='reservedate',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
