# Generated by Django 3.2.7 on 2021-10-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_remove_reservedate_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedate',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
