# Generated by Django 3.2.7 on 2021-10-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_escaperoom_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escaperoom',
            name='genre',
            field=models.CharField(max_length=20),
        ),
    ]
