# Generated by Django 3.2.7 on 2021-10-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_alter_escaperoom_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escaperoom',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
