# Generated by Django 3.2.7 on 2021-10-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_auto_20211003_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedate',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.player'),
        ),
    ]
