# Generated by Django 3.2.7 on 2021-10-17 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_auto_20211017_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservetime',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.escaperoom'),
        ),
        migrations.AddField(
            model_name='reservetime',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.player'),
        ),
    ]
