# Generated by Django 3.2.7 on 2021-10-17 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_alter_reservetime_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservetime',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservetime',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.escaperoom'),
        ),
        migrations.AlterField(
            model_name='reservetime',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.player'),
        ),
    ]
