# Generated by Django 3.2.7 on 2021-10-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_escaperoom_hardship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escaperoom',
            name='number_of_players',
        ),
    ]
