# Generated by Django 3.2.7 on 2021-10-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0035_remove_escaperoom_number_of_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escaperoom',
            old_name='price',
            new_name='price_per_player',
        ),
        migrations.AddField(
            model_name='escaperoom',
            name='pre_price',
            field=models.IntegerField(null=True),
        ),
    ]
