# Generated by Django 3.2.7 on 2021-10-11 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('img', models.ImageField(upload_to='img', verbose_name='تصویر مقاله')),
                ('descriptions', models.TextField(verbose_name='محتوا مقاله')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='ادرس URL')),
                ('creat', models.DateTimeField(verbose_name='زمان ایجاد ')),
                ('publish', models.TimeField(verbose_name='زمان انتشار')),
                ('update', models.TimeField(verbose_name='زمان اپدیت')),
                ('status', models.BooleanField(default=True, verbose_name='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده مقاله')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
