# Generated by Django 3.2.7 on 2021-10-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='phone',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
