# Generated by Django 3.2.7 on 2021-10-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_payment', '0002_prepayment_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepayment',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
