# Generated by Django 3.2.7 on 2021-10-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_payment', '0003_alter_prepayment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepayment',
            name='time',
            field=models.CharField(max_length=15),
        ),
    ]
